
%\VignetteIndexEntry{Bioconductor LaTeX Style}
%\VignettePackage{BiocStyle}
%\VignetteEngine{knitr::knitr}

\documentclass{article}
<<style-Sweave, eval=TRUE, echo=FALSE, results='asis'>>=
BiocStyle::latex()
@
\usepackage{url}

\title{Robert Bentham}
\author{MCbiclust 0.99.33}
\begin{document}

<<include=FALSE>>=
library(knitr)
opts_chunk$set(
concordance=TRUE
)
@


\maketitle

\tableofcontents

\section{Introduction}

\section{Session Info}
<<results='asis'>>=
toLatex(sessionInfo())
@



\bibliography{bibvignette}

\end{document}
